
//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// 
//------------------------------------------------------------------------------

// Generated from: org/waveprotocol/wave/examples/fedone/waveserver/waveclient-rpc.proto
// Note: requires additional types generated from: org/waveprotocol/wave/protocol/common.proto
// Note: requires additional types generated from: org/waveprotocol/wave/examples/fedone/rpc/rpc.proto
namespace ObjectCloud.Wave.ProtocolBuffers.Waveserver
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ProtocolOpenRequest")]
    public partial class ProtocolOpenRequest : global::ProtoBuf.IExtensible
    {
        public ProtocolOpenRequest() { }

        private string _participant_id;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"participant_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string participant_id
        {
            get { return _participant_id; }
            set { _participant_id = value; }
        }
        private string _wave_id;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"wave_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string wave_id
        {
            get { return _wave_id; }
            set { _wave_id = value; }
        }
        private readonly global::System.Collections.Generic.List<string> _wavelet_id_prefix = new global::System.Collections.Generic.List<string>();
        [global::ProtoBuf.ProtoMember(3, Name = @"wavelet_id_prefix", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<string> wavelet_id_prefix
        {
            get { return _wavelet_id_prefix; }
        }


        private int _maximum_wavelets = default(int);
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"maximum_wavelets", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int maximum_wavelets
        {
            get { return _maximum_wavelets; }
            set { _maximum_wavelets = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ProtocolWaveletUpdate")]
    public partial class ProtocolWaveletUpdate : global::ProtoBuf.IExtensible
    {
        public ProtocolWaveletUpdate() { }

        private string _wavelet_name;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"wavelet_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string wavelet_name
        {
            get { return _wavelet_name; }
            set { _wavelet_name = value; }
        }
        private readonly global::System.Collections.Generic.List<ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolWaveletDelta> _applied_delta = new global::System.Collections.Generic.List<ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolWaveletDelta>();
        [global::ProtoBuf.ProtoMember(2, Name = @"applied_delta", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolWaveletDelta> applied_delta
        {
            get { return _applied_delta; }
        }


        private ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolHashedVersion _commit_notice = null;
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"commit_notice", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolHashedVersion commit_notice
        {
            get { return _commit_notice; }
            set { _commit_notice = value; }
        }

        private ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolHashedVersion _resulting_version = null;
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"resulting_version", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolHashedVersion resulting_version
        {
            get { return _resulting_version; }
            set { _resulting_version = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ProtocolSubmitRequest")]
    public partial class ProtocolSubmitRequest : global::ProtoBuf.IExtensible
    {
        public ProtocolSubmitRequest() { }

        private string _wavelet_name;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"wavelet_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string wavelet_name
        {
            get { return _wavelet_name; }
            set { _wavelet_name = value; }
        }
        private ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolWaveletDelta _delta;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"delta", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolWaveletDelta delta
        {
            get { return _delta; }
            set { _delta = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ProtocolSubmitResponse")]
    public partial class ProtocolSubmitResponse : global::ProtoBuf.IExtensible
    {
        public ProtocolSubmitResponse() { }

        private int _operations_applied;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"operations_applied", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int operations_applied
        {
            get { return _operations_applied; }
            set { _operations_applied = value; }
        }

        private string _error_message = "";
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"error_message", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string error_message
        {
            get { return _error_message; }
            set { _error_message = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    public interface IProtocolWaveClientRpc
    {
        ObjectCloud.Wave.ProtocolBuffers.Waveserver.ProtocolWaveletUpdate Open(ObjectCloud.Wave.ProtocolBuffers.Waveserver.ProtocolOpenRequest request);
        ObjectCloud.Wave.ProtocolBuffers.Waveserver.ProtocolSubmitResponse Submit(ObjectCloud.Wave.ProtocolBuffers.Waveserver.ProtocolSubmitRequest request);

    }


}