
//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// 
//------------------------------------------------------------------------------

// Generated from: org/waveprotocol/wave/protocol/common.proto
namespace ObjectCloud.Wave.ProtocolBuffers.Protocol
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ProtocolWaveletDelta")]
    public partial class ProtocolWaveletDelta : global::ProtoBuf.IExtensible
    {
        public ProtocolWaveletDelta() { }

        private ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolHashedVersion _hashed_version;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"hashed_version", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolHashedVersion hashed_version
        {
            get { return _hashed_version; }
            set { _hashed_version = value; }
        }
        private string _author;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"author", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string author
        {
            get { return _author; }
            set { _author = value; }
        }
        private readonly global::System.Collections.Generic.List<ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolWaveletOperation> _operation = new global::System.Collections.Generic.List<ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolWaveletOperation>();
        [global::ProtoBuf.ProtoMember(3, Name = @"operation", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolWaveletOperation> operation
        {
            get { return _operation; }
        }

        private readonly global::System.Collections.Generic.List<string> _address_path = new global::System.Collections.Generic.List<string>();
        [global::ProtoBuf.ProtoMember(4, Name = @"address_path", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<string> address_path
        {
            get { return _address_path; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ProtocolHashedVersion")]
    public partial class ProtocolHashedVersion : global::ProtoBuf.IExtensible
    {
        public ProtocolHashedVersion() { }

        private long _version;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public long version
        {
            get { return _version; }
            set { _version = value; }
        }
        private byte[] _history_hash;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"history_hash", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public byte[] history_hash
        {
            get { return _history_hash; }
            set { _history_hash = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ProtocolWaveletOperation")]
    public partial class ProtocolWaveletOperation : global::ProtoBuf.IExtensible
    {
        public ProtocolWaveletOperation() { }


        private string _add_participant = "";
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"add_participant", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string add_participant
        {
            get { return _add_participant; }
            set { _add_participant = value; }
        }

        private string _remove_participant = "";
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"remove_participant", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string remove_participant
        {
            get { return _remove_participant; }
            set { _remove_participant = value; }
        }

        private ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolWaveletOperation.MutateDocument _mutate_document = null;
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"mutate_document", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolWaveletOperation.MutateDocument mutate_document
        {
            get { return _mutate_document; }
            set { _mutate_document = value; }
        }

        private bool _no_op = default(bool);
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"no_op", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(default(bool))]
        public bool no_op
        {
            get { return _no_op; }
            set { _no_op = value; }
        }
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"MutateDocument")]
        public partial class MutateDocument : global::ProtoBuf.IExtensible
        {
            public MutateDocument() { }

            private string _document_id;
            [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"document_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public string document_id
            {
                get { return _document_id; }
                set { _document_id = value; }
            }
            private ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation _document_operation;
            [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"document_operation", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation document_operation
            {
                get { return _document_operation; }
                set { _document_operation = value; }
            }
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ProtocolDocumentOperation")]
    public partial class ProtocolDocumentOperation : global::ProtoBuf.IExtensible
    {
        public ProtocolDocumentOperation() { }

        private readonly global::System.Collections.Generic.List<ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation.Component> _component = new global::System.Collections.Generic.List<ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation.Component>();
        [global::ProtoBuf.ProtoMember(1, Name = @"component", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation.Component> component
        {
            get { return _component; }
        }

        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"Component")]
        public partial class Component : global::ProtoBuf.IExtensible
        {
            public Component() { }


            private ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation.Component.AnnotationBoundary _annotation_boundary = null;
            [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"annotation_boundary", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue(null)]
            public ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation.Component.AnnotationBoundary annotation_boundary
            {
                get { return _annotation_boundary; }
                set { _annotation_boundary = value; }
            }

            private string _characters = "";
            [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"characters", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string characters
            {
                get { return _characters; }
                set { _characters = value; }
            }

            private ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation.Component.ElementStart _element_start = null;
            [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"element_start", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue(null)]
            public ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation.Component.ElementStart element_start
            {
                get { return _element_start; }
                set { _element_start = value; }
            }

            private bool _element_end = default(bool);
            [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"element_end", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue(default(bool))]
            public bool element_end
            {
                get { return _element_end; }
                set { _element_end = value; }
            }

            private int _retain_item_count = default(int);
            [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"retain_item_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int retain_item_count
            {
                get { return _retain_item_count; }
                set { _retain_item_count = value; }
            }

            private string _delete_characters = "";
            [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name = @"delete_characters", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string delete_characters
            {
                get { return _delete_characters; }
                set { _delete_characters = value; }
            }

            private ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation.Component.ElementStart _delete_element_start = null;
            [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name = @"delete_element_start", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue(null)]
            public ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation.Component.ElementStart delete_element_start
            {
                get { return _delete_element_start; }
                set { _delete_element_start = value; }
            }

            private bool _delete_element_end = default(bool);
            [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name = @"delete_element_end", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue(default(bool))]
            public bool delete_element_end
            {
                get { return _delete_element_end; }
                set { _delete_element_end = value; }
            }

            private ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation.Component.ReplaceAttributes _replace_attributes = null;
            [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name = @"replace_attributes", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue(null)]
            public ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation.Component.ReplaceAttributes replace_attributes
            {
                get { return _replace_attributes; }
                set { _replace_attributes = value; }
            }

            private ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation.Component.UpdateAttributes _update_attributes = null;
            [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name = @"update_attributes", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue(null)]
            public ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation.Component.UpdateAttributes update_attributes
            {
                get { return _update_attributes; }
                set { _update_attributes = value; }
            }
            [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"KeyValuePair")]
            public partial class KeyValuePair : global::ProtoBuf.IExtensible
            {
                public KeyValuePair() { }

                private string _key;
                [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
                public string key
                {
                    get { return _key; }
                    set { _key = value; }
                }
                private string _value;
                [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
                public string value
                {
                    get { return _value; }
                    set { _value = value; }
                }
                private global::ProtoBuf.IExtension extensionObject;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
            }

            [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"KeyValueUpdate")]
            public partial class KeyValueUpdate : global::ProtoBuf.IExtensible
            {
                public KeyValueUpdate() { }

                private string _key;
                [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
                public string key
                {
                    get { return _key; }
                    set { _key = value; }
                }

                private string _old_value = "";
                [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"old_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
                [global::System.ComponentModel.DefaultValue("")]
                public string old_value
                {
                    get { return _old_value; }
                    set { _old_value = value; }
                }

                private string _new_value = "";
                [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"new_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
                [global::System.ComponentModel.DefaultValue("")]
                public string new_value
                {
                    get { return _new_value; }
                    set { _new_value = value; }
                }
                private global::ProtoBuf.IExtension extensionObject;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
            }

            [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ElementStart")]
            public partial class ElementStart : global::ProtoBuf.IExtensible
            {
                public ElementStart() { }

                private string _type;
                [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
                public string type
                {
                    get { return _type; }
                    set { _type = value; }
                }
                private readonly global::System.Collections.Generic.List<ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation.Component.KeyValuePair> _attribute = new global::System.Collections.Generic.List<ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation.Component.KeyValuePair>();
                [global::ProtoBuf.ProtoMember(2, Name = @"attribute", DataFormat = global::ProtoBuf.DataFormat.Default)]
                public global::System.Collections.Generic.List<ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation.Component.KeyValuePair> attribute
                {
                    get { return _attribute; }
                }

                private global::ProtoBuf.IExtension extensionObject;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
            }

            [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ReplaceAttributes")]
            public partial class ReplaceAttributes : global::ProtoBuf.IExtensible
            {
                public ReplaceAttributes() { }


                private bool _empty = default(bool);
                [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"empty", DataFormat = global::ProtoBuf.DataFormat.Default)]
                [global::System.ComponentModel.DefaultValue(default(bool))]
                public bool empty
                {
                    get { return _empty; }
                    set { _empty = value; }
                }
                private readonly global::System.Collections.Generic.List<ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation.Component.KeyValuePair> _old_attribute = new global::System.Collections.Generic.List<ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation.Component.KeyValuePair>();
                [global::ProtoBuf.ProtoMember(2, Name = @"old_attribute", DataFormat = global::ProtoBuf.DataFormat.Default)]
                public global::System.Collections.Generic.List<ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation.Component.KeyValuePair> old_attribute
                {
                    get { return _old_attribute; }
                }

                private readonly global::System.Collections.Generic.List<ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation.Component.KeyValuePair> _new_attribute = new global::System.Collections.Generic.List<ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation.Component.KeyValuePair>();
                [global::ProtoBuf.ProtoMember(3, Name = @"new_attribute", DataFormat = global::ProtoBuf.DataFormat.Default)]
                public global::System.Collections.Generic.List<ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation.Component.KeyValuePair> new_attribute
                {
                    get { return _new_attribute; }
                }

                private global::ProtoBuf.IExtension extensionObject;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
            }

            [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"UpdateAttributes")]
            public partial class UpdateAttributes : global::ProtoBuf.IExtensible
            {
                public UpdateAttributes() { }


                private bool _empty = default(bool);
                [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"empty", DataFormat = global::ProtoBuf.DataFormat.Default)]
                [global::System.ComponentModel.DefaultValue(default(bool))]
                public bool empty
                {
                    get { return _empty; }
                    set { _empty = value; }
                }
                private readonly global::System.Collections.Generic.List<ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation.Component.KeyValueUpdate> _attribute_update = new global::System.Collections.Generic.List<ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation.Component.KeyValueUpdate>();
                [global::ProtoBuf.ProtoMember(2, Name = @"attribute_update", DataFormat = global::ProtoBuf.DataFormat.Default)]
                public global::System.Collections.Generic.List<ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation.Component.KeyValueUpdate> attribute_update
                {
                    get { return _attribute_update; }
                }

                private global::ProtoBuf.IExtension extensionObject;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
            }

            [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"AnnotationBoundary")]
            public partial class AnnotationBoundary : global::ProtoBuf.IExtensible
            {
                public AnnotationBoundary() { }


                private bool _empty = default(bool);
                [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"empty", DataFormat = global::ProtoBuf.DataFormat.Default)]
                [global::System.ComponentModel.DefaultValue(default(bool))]
                public bool empty
                {
                    get { return _empty; }
                    set { _empty = value; }
                }
                private readonly global::System.Collections.Generic.List<string> _end = new global::System.Collections.Generic.List<string>();
                [global::ProtoBuf.ProtoMember(2, Name = @"end", DataFormat = global::ProtoBuf.DataFormat.Default)]
                public global::System.Collections.Generic.List<string> end
                {
                    get { return _end; }
                }

                private readonly global::System.Collections.Generic.List<ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation.Component.KeyValueUpdate> _change = new global::System.Collections.Generic.List<ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation.Component.KeyValueUpdate>();
                [global::ProtoBuf.ProtoMember(3, Name = @"change", DataFormat = global::ProtoBuf.DataFormat.Default)]
                public global::System.Collections.Generic.List<ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolDocumentOperation.Component.KeyValueUpdate> change
                {
                    get { return _change; }
                }

                private global::ProtoBuf.IExtension extensionObject;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
            }

            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ProtocolAppliedWaveletDelta")]
    public partial class ProtocolAppliedWaveletDelta : global::ProtoBuf.IExtensible
    {
        public ProtocolAppliedWaveletDelta() { }

        private ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolSignedDelta _signed_original_delta;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"signed_original_delta", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolSignedDelta signed_original_delta
        {
            get { return _signed_original_delta; }
            set { _signed_original_delta = value; }
        }

        private ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolHashedVersion _hashed_version_applied_at = null;
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"hashed_version_applied_at", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolHashedVersion hashed_version_applied_at
        {
            get { return _hashed_version_applied_at; }
            set { _hashed_version_applied_at = value; }
        }
        private int _operations_applied;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"operations_applied", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int operations_applied
        {
            get { return _operations_applied; }
            set { _operations_applied = value; }
        }
        private long _application_timestamp;
        [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name = @"application_timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public long application_timestamp
        {
            get { return _application_timestamp; }
            set { _application_timestamp = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ProtocolSignedDelta")]
    public partial class ProtocolSignedDelta : global::ProtoBuf.IExtensible
    {
        public ProtocolSignedDelta() { }

        private byte[] _delta;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"delta", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public byte[] delta
        {
            get { return _delta; }
            set { _delta = value; }
        }
        private readonly global::System.Collections.Generic.List<ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolSignature> _signature = new global::System.Collections.Generic.List<ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolSignature>();
        [global::ProtoBuf.ProtoMember(2, Name = @"signature", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolSignature> signature
        {
            get { return _signature; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ProtocolSignature")]
    public partial class ProtocolSignature : global::ProtoBuf.IExtensible
    {
        public ProtocolSignature() { }

        private byte[] _signature_bytes;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"signature_bytes", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public byte[] signature_bytes
        {
            get { return _signature_bytes; }
            set { _signature_bytes = value; }
        }
        private byte[] _signer_id;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"signer_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public byte[] signer_id
        {
            get { return _signer_id; }
            set { _signer_id = value; }
        }
        private ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolSignature.SignatureAlgorithm _signature_algorithm;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"signature_algorithm", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolSignature.SignatureAlgorithm signature_algorithm
        {
            get { return _signature_algorithm; }
            set { _signature_algorithm = value; }
        }
        public enum SignatureAlgorithm
        {
            SHA1_RSA = 1
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ProtocolSignerInfo")]
    public partial class ProtocolSignerInfo : global::ProtoBuf.IExtensible
    {
        public ProtocolSignerInfo() { }

        private ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolSignerInfo.HashAlgorithm _hash_algorithm;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"hash_algorithm", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public ObjectCloud.Wave.ProtocolBuffers.Protocol.ProtocolSignerInfo.HashAlgorithm hash_algorithm
        {
            get { return _hash_algorithm; }
            set { _hash_algorithm = value; }
        }
        private string _domain;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"domain", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string domain
        {
            get { return _domain; }
            set { _domain = value; }
        }
        private readonly global::System.Collections.Generic.List<byte[]> _certificate = new global::System.Collections.Generic.List<byte[]>();
        [global::ProtoBuf.ProtoMember(3, Name = @"certificate", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<byte[]> certificate
        {
            get { return _certificate; }
        }

        public enum HashAlgorithm
        {
            SHA256 = 1,
            SHA512 = 2
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

}